# .github/workflows/deploy.yml
name: 📦 Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out your repo
      - uses: actions/checkout@v3

      # 2. Install Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      # 3. Install dependencies
      - run: npm ci

      # 4. Run your build
      - run: npm run build

      # 5. Deploy to gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist            # Astro’s output directory
          cname: popgen.ca               # writes CNAME file for you
