# .github/workflows/deploy.yml
name: 📦 Build & Deploy

# Grant the token explicit write access
permissions:
  contents: write     # needed to push to gh-pages
  pages: write        # needed if you're using GitHub Pages API
  id-token: write     # not strictly required here, but good practice

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - run: npm ci
      - run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: popgen.ca
      - name: Check HTTPS redirect
        run: |
          echo "Checking popgen.ca redirects to HTTPS…"
          status=$(curl -o /dev/null -s -w "%{http_code}" http://popgen.ca)
          if [ "$status" != "301" ] && [ "$status" != "302" ]; then
            echo "::warning file=README.md::popgen.ca did not redirect HTTP → HTTPS (status $status)"
          else
            echo "HTTP → HTTPS redirect OK (status $status)"
          fi